/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgrimarketRouteImport } from './routes/agrimarket'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgrimarketIndexRouteImport } from './routes/agrimarket.index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AgrimarketTransportRouteImport } from './routes/agrimarket.transport'
import { Route as AgrimarketSetupWizardRouteImport } from './routes/agrimarket.setup-wizard'
import { Route as AgrimarketSetupRouteImport } from './routes/agrimarket.setup'
import { Route as AgrimarketPostRouteImport } from './routes/agrimarket.post'
import { Route as AgrimarketNotificationsRouteImport } from './routes/agrimarket.notifications'
import { Route as AgrimarketMyRequestsRouteImport } from './routes/agrimarket.my-requests'
import { Route as AgrimarketImpactRouteImport } from './routes/agrimarket.impact'
import { Route as AgrimarketDoctorRouteImport } from './routes/agrimarket.doctor'
import { Route as AgrimarketAnalyticsRouteImport } from './routes/agrimarket.analytics'
import { Route as AgrimarketAiInsightsRouteImport } from './routes/agrimarket.ai-insights'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardTraderRouteImport } from './routes/_authenticated/dashboard.trader'
import { Route as AuthenticatedDashboardStudentRouteImport } from './routes/_authenticated/dashboard.student'
import { Route as AuthenticatedDashboardOfficerRouteImport } from './routes/_authenticated/dashboard.officer'
import { Route as AuthenticatedDashboardFarmerRouteImport } from './routes/_authenticated/dashboard.farmer'
import { Route as AuthenticatedDashboardBuyerRouteImport } from './routes/_authenticated/dashboard.buyer'
import { Route as AuthenticatedDashboardAgribusinessRouteImport } from './routes/_authenticated/dashboard.agribusiness'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgrimarketRoute = AgrimarketRouteImport.update({
  id: '/agrimarket',
  path: '/agrimarket',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgrimarketIndexRoute = AgrimarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgrimarketRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgrimarketTransportRoute = AgrimarketTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AgrimarketSetupWizardRoute = AgrimarketSetupWizardRouteImport.update({
  id: '/setup-wizard',
  path: '/setup-wizard',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AgrimarketSetupRoute = AgrimarketSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AgrimarketPostRoute = AgrimarketPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AgrimarketNotificationsRoute = AgrimarketNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AgrimarketMyRequestsRoute = AgrimarketMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AgrimarketImpactRoute = AgrimarketImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AgrimarketDoctorRoute = AgrimarketDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AgrimarketAnalyticsRoute = AgrimarketAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AgrimarketAiInsightsRoute = AgrimarketAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AgrimarketRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTraderRoute =
  AuthenticatedDashboardTraderRouteImport.update({
    id: '/dashboard/trader',
    path: '/dashboard/trader',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentRoute =
  AuthenticatedDashboardStudentRouteImport.update({
    id: '/dashboard/student',
    path: '/dashboard/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardOfficerRoute =
  AuthenticatedDashboardOfficerRouteImport.update({
    id: '/dashboard/officer',
    path: '/dashboard/officer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardFarmerRoute =
  AuthenticatedDashboardFarmerRouteImport.update({
    id: '/dashboard/farmer',
    path: '/dashboard/farmer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBuyerRoute =
  AuthenticatedDashboardBuyerRouteImport.update({
    id: '/dashboard/buyer',
    path: '/dashboard/buyer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAgribusinessRoute =
  AuthenticatedDashboardAgribusinessRouteImport.update({
    id: '/dashboard/agribusiness',
    path: '/dashboard/agribusiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agrimarket': typeof AgrimarketRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/agrimarket/ai-insights': typeof AgrimarketAiInsightsRoute
  '/agrimarket/analytics': typeof AgrimarketAnalyticsRoute
  '/agrimarket/doctor': typeof AgrimarketDoctorRoute
  '/agrimarket/impact': typeof AgrimarketImpactRoute
  '/agrimarket/my-requests': typeof AgrimarketMyRequestsRoute
  '/agrimarket/notifications': typeof AgrimarketNotificationsRoute
  '/agrimarket/post': typeof AgrimarketPostRoute
  '/agrimarket/setup': typeof AgrimarketSetupRoute
  '/agrimarket/setup-wizard': typeof AgrimarketSetupWizardRoute
  '/agrimarket/transport': typeof AgrimarketTransportRoute
  '/api/chat': typeof ApiChatRoute
  '/agrimarket/': typeof AgrimarketIndexRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/agribusiness': typeof AuthenticatedDashboardAgribusinessRoute
  '/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/dashboard/farmer': typeof AuthenticatedDashboardFarmerRoute
  '/dashboard/officer': typeof AuthenticatedDashboardOfficerRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard/trader': typeof AuthenticatedDashboardTraderRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/agrimarket/ai-insights': typeof AgrimarketAiInsightsRoute
  '/agrimarket/analytics': typeof AgrimarketAnalyticsRoute
  '/agrimarket/doctor': typeof AgrimarketDoctorRoute
  '/agrimarket/impact': typeof AgrimarketImpactRoute
  '/agrimarket/my-requests': typeof AgrimarketMyRequestsRoute
  '/agrimarket/notifications': typeof AgrimarketNotificationsRoute
  '/agrimarket/post': typeof AgrimarketPostRoute
  '/agrimarket/setup': typeof AgrimarketSetupRoute
  '/agrimarket/setup-wizard': typeof AgrimarketSetupWizardRoute
  '/agrimarket/transport': typeof AgrimarketTransportRoute
  '/api/chat': typeof ApiChatRoute
  '/agrimarket': typeof AgrimarketIndexRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/agribusiness': typeof AuthenticatedDashboardAgribusinessRoute
  '/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/dashboard/farmer': typeof AuthenticatedDashboardFarmerRoute
  '/dashboard/officer': typeof AuthenticatedDashboardOfficerRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard/trader': typeof AuthenticatedDashboardTraderRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agrimarket': typeof AgrimarketRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/agrimarket/ai-insights': typeof AgrimarketAiInsightsRoute
  '/agrimarket/analytics': typeof AgrimarketAnalyticsRoute
  '/agrimarket/doctor': typeof AgrimarketDoctorRoute
  '/agrimarket/impact': typeof AgrimarketImpactRoute
  '/agrimarket/my-requests': typeof AgrimarketMyRequestsRoute
  '/agrimarket/notifications': typeof AgrimarketNotificationsRoute
  '/agrimarket/post': typeof AgrimarketPostRoute
  '/agrimarket/setup': typeof AgrimarketSetupRoute
  '/agrimarket/setup-wizard': typeof AgrimarketSetupWizardRoute
  '/agrimarket/transport': typeof AgrimarketTransportRoute
  '/api/chat': typeof ApiChatRoute
  '/agrimarket/': typeof AgrimarketIndexRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/agribusiness': typeof AuthenticatedDashboardAgribusinessRoute
  '/_authenticated/dashboard/buyer': typeof AuthenticatedDashboardBuyerRoute
  '/_authenticated/dashboard/farmer': typeof AuthenticatedDashboardFarmerRoute
  '/_authenticated/dashboard/officer': typeof AuthenticatedDashboardOfficerRoute
  '/_authenticated/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/_authenticated/dashboard/trader': typeof AuthenticatedDashboardTraderRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agrimarket'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/profile'
    | '/agrimarket/ai-insights'
    | '/agrimarket/analytics'
    | '/agrimarket/doctor'
    | '/agrimarket/impact'
    | '/agrimarket/my-requests'
    | '/agrimarket/notifications'
    | '/agrimarket/post'
    | '/agrimarket/setup'
    | '/agrimarket/setup-wizard'
    | '/agrimarket/transport'
    | '/api/chat'
    | '/agrimarket/'
    | '/dashboard/admin'
    | '/dashboard/agribusiness'
    | '/dashboard/buyer'
    | '/dashboard/farmer'
    | '/dashboard/officer'
    | '/dashboard/student'
    | '/dashboard/trader'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/profile'
    | '/agrimarket/ai-insights'
    | '/agrimarket/analytics'
    | '/agrimarket/doctor'
    | '/agrimarket/impact'
    | '/agrimarket/my-requests'
    | '/agrimarket/notifications'
    | '/agrimarket/post'
    | '/agrimarket/setup'
    | '/agrimarket/setup-wizard'
    | '/agrimarket/transport'
    | '/api/chat'
    | '/agrimarket'
    | '/dashboard/admin'
    | '/dashboard/agribusiness'
    | '/dashboard/buyer'
    | '/dashboard/farmer'
    | '/dashboard/officer'
    | '/dashboard/student'
    | '/dashboard/trader'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agrimarket'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/profile'
    | '/agrimarket/ai-insights'
    | '/agrimarket/analytics'
    | '/agrimarket/doctor'
    | '/agrimarket/impact'
    | '/agrimarket/my-requests'
    | '/agrimarket/notifications'
    | '/agrimarket/post'
    | '/agrimarket/setup'
    | '/agrimarket/setup-wizard'
    | '/agrimarket/transport'
    | '/api/chat'
    | '/agrimarket/'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/agribusiness'
    | '/_authenticated/dashboard/buyer'
    | '/_authenticated/dashboard/farmer'
    | '/_authenticated/dashboard/officer'
    | '/_authenticated/dashboard/student'
    | '/_authenticated/dashboard/trader'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgrimarketRoute: typeof AgrimarketRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agrimarket': {
      id: '/agrimarket'
      path: '/agrimarket'
      fullPath: '/agrimarket'
      preLoaderRoute: typeof AgrimarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agrimarket/': {
      id: '/agrimarket/'
      path: '/'
      fullPath: '/agrimarket/'
      preLoaderRoute: typeof AgrimarketIndexRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agrimarket/transport': {
      id: '/agrimarket/transport'
      path: '/transport'
      fullPath: '/agrimarket/transport'
      preLoaderRoute: typeof AgrimarketTransportRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/agrimarket/setup-wizard': {
      id: '/agrimarket/setup-wizard'
      path: '/setup-wizard'
      fullPath: '/agrimarket/setup-wizard'
      preLoaderRoute: typeof AgrimarketSetupWizardRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/agrimarket/setup': {
      id: '/agrimarket/setup'
      path: '/setup'
      fullPath: '/agrimarket/setup'
      preLoaderRoute: typeof AgrimarketSetupRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/agrimarket/post': {
      id: '/agrimarket/post'
      path: '/post'
      fullPath: '/agrimarket/post'
      preLoaderRoute: typeof AgrimarketPostRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/agrimarket/notifications': {
      id: '/agrimarket/notifications'
      path: '/notifications'
      fullPath: '/agrimarket/notifications'
      preLoaderRoute: typeof AgrimarketNotificationsRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/agrimarket/my-requests': {
      id: '/agrimarket/my-requests'
      path: '/my-requests'
      fullPath: '/agrimarket/my-requests'
      preLoaderRoute: typeof AgrimarketMyRequestsRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/agrimarket/impact': {
      id: '/agrimarket/impact'
      path: '/impact'
      fullPath: '/agrimarket/impact'
      preLoaderRoute: typeof AgrimarketImpactRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/agrimarket/doctor': {
      id: '/agrimarket/doctor'
      path: '/doctor'
      fullPath: '/agrimarket/doctor'
      preLoaderRoute: typeof AgrimarketDoctorRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/agrimarket/analytics': {
      id: '/agrimarket/analytics'
      path: '/analytics'
      fullPath: '/agrimarket/analytics'
      preLoaderRoute: typeof AgrimarketAnalyticsRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/agrimarket/ai-insights': {
      id: '/agrimarket/ai-insights'
      path: '/ai-insights'
      fullPath: '/agrimarket/ai-insights'
      preLoaderRoute: typeof AgrimarketAiInsightsRouteImport
      parentRoute: typeof AgrimarketRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/trader': {
      id: '/_authenticated/dashboard/trader'
      path: '/dashboard/trader'
      fullPath: '/dashboard/trader'
      preLoaderRoute: typeof AuthenticatedDashboardTraderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student': {
      id: '/_authenticated/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthenticatedDashboardStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/officer': {
      id: '/_authenticated/dashboard/officer'
      path: '/dashboard/officer'
      fullPath: '/dashboard/officer'
      preLoaderRoute: typeof AuthenticatedDashboardOfficerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/farmer': {
      id: '/_authenticated/dashboard/farmer'
      path: '/dashboard/farmer'
      fullPath: '/dashboard/farmer'
      preLoaderRoute: typeof AuthenticatedDashboardFarmerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/buyer': {
      id: '/_authenticated/dashboard/buyer'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer'
      preLoaderRoute: typeof AuthenticatedDashboardBuyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/agribusiness': {
      id: '/_authenticated/dashboard/agribusiness'
      path: '/dashboard/agribusiness'
      fullPath: '/dashboard/agribusiness'
      preLoaderRoute: typeof AuthenticatedDashboardAgribusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardAgribusinessRoute: typeof AuthenticatedDashboardAgribusinessRoute
  AuthenticatedDashboardBuyerRoute: typeof AuthenticatedDashboardBuyerRoute
  AuthenticatedDashboardFarmerRoute: typeof AuthenticatedDashboardFarmerRoute
  AuthenticatedDashboardOfficerRoute: typeof AuthenticatedDashboardOfficerRoute
  AuthenticatedDashboardStudentRoute: typeof AuthenticatedDashboardStudentRoute
  AuthenticatedDashboardTraderRoute: typeof AuthenticatedDashboardTraderRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardAgribusinessRoute:
    AuthenticatedDashboardAgribusinessRoute,
  AuthenticatedDashboardBuyerRoute: AuthenticatedDashboardBuyerRoute,
  AuthenticatedDashboardFarmerRoute: AuthenticatedDashboardFarmerRoute,
  AuthenticatedDashboardOfficerRoute: AuthenticatedDashboardOfficerRoute,
  AuthenticatedDashboardStudentRoute: AuthenticatedDashboardStudentRoute,
  AuthenticatedDashboardTraderRoute: AuthenticatedDashboardTraderRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AgrimarketRouteChildren {
  AgrimarketAiInsightsRoute: typeof AgrimarketAiInsightsRoute
  AgrimarketAnalyticsRoute: typeof AgrimarketAnalyticsRoute
  AgrimarketDoctorRoute: typeof AgrimarketDoctorRoute
  AgrimarketImpactRoute: typeof AgrimarketImpactRoute
  AgrimarketMyRequestsRoute: typeof AgrimarketMyRequestsRoute
  AgrimarketNotificationsRoute: typeof AgrimarketNotificationsRoute
  AgrimarketPostRoute: typeof AgrimarketPostRoute
  AgrimarketSetupRoute: typeof AgrimarketSetupRoute
  AgrimarketSetupWizardRoute: typeof AgrimarketSetupWizardRoute
  AgrimarketTransportRoute: typeof AgrimarketTransportRoute
  AgrimarketIndexRoute: typeof AgrimarketIndexRoute
}

const AgrimarketRouteChildren: AgrimarketRouteChildren = {
  AgrimarketAiInsightsRoute: AgrimarketAiInsightsRoute,
  AgrimarketAnalyticsRoute: AgrimarketAnalyticsRoute,
  AgrimarketDoctorRoute: AgrimarketDoctorRoute,
  AgrimarketImpactRoute: AgrimarketImpactRoute,
  AgrimarketMyRequestsRoute: AgrimarketMyRequestsRoute,
  AgrimarketNotificationsRoute: AgrimarketNotificationsRoute,
  AgrimarketPostRoute: AgrimarketPostRoute,
  AgrimarketSetupRoute: AgrimarketSetupRoute,
  AgrimarketSetupWizardRoute: AgrimarketSetupWizardRoute,
  AgrimarketTransportRoute: AgrimarketTransportRoute,
  AgrimarketIndexRoute: AgrimarketIndexRoute,
}

const AgrimarketRouteWithChildren = AgrimarketRoute._addFileChildren(
  AgrimarketRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgrimarketRoute: AgrimarketRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
